[package]
name = "indexlake-index-bm25"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "IndexLake bm25 index"

[dependencies]
indexlake = { workspace = true }

arrow = { workspace = true }
async-trait = { workspace = true }
bm25 = { workspace = true }
futures = { workspace = true }
jieba-rs = { workspace = true }
parquet = { workspace = true, features = ["async"] }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
