[package]
name = "indexlake-datafusion-gen"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Code generation for proto"
publish = false

[dependencies]
prost-build = { workspace = true }