[package]
name = "indexlake-benchmarks"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
indexlake = { workspace = true }
indexlake-catalog-postgres = { workspace = true }
indexlake-catalog-sqlite = { workspace = true }
indexlake-index-bm25 = { workspace = true }
indexlake-index-btree = { workspace = true }
indexlake-index-rstar = { workspace = true }
indexlake-integration-tests = { workspace = true }

arrow = { workspace = true }
delta_kernel = { version = "0.13.0", features = ["arrow-conversion"] }
deltalake = { version = "0.27.0", features = ["datafusion"] }
deltalake-aws = { version = "0.10.0", default-features = false }
futures = { workspace = true }
lance = "0.31.1"
lance-core = "0.31.1"
lance-datafusion = "0.31.1"
lance-index = { version = "0.31.1", features = ["tokenizer-jieba"] }
lance-io = "0.31.1"
lance-linalg = "0.31.1"
lance-table = "0.31.1"
tokio = { workspace = true, features = ["full"] }
num_cpus = { workspace = true }

[[bin]]
name = "indexlake"
path = "src/bin/indexlake.rs"

[[bin]]
name = "deltalake"
path = "src/bin/deltalake.rs"

[[bin]]
name = "lance"
path = "src/bin/lance.rs"