name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Build Dependencies
        run: |
          apt-get update
          apt-get install -y protobuf-compiler

      - name: Run cargo check
        run: cargo check

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Build Dependencies
        run: |
          apt-get update
          apt-get install -y protobuf-compiler

      - name: Run cargo test
        run: cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      # - name: Run cargo clippy
      #   run: cargo clippy --all -- -D warnings